on:
  workflow_dispatch:
  push:
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name:
        run: |        
          npm i -g ngrok
          ngrok config add-authtoken ${{secrets.NGROK_TOKEN}}
          ngrok http --domain=secure-pipefish-seriously.ngrok-free.app 80
